truncate table [dbo].[DailyTransactionsBOB]
truncate table [dbo].[DailyTransactionsBOI]
truncate table [dbo].[DailyTransactionsBOM]
truncate table [dbo].[DailyTransactionsBRKGB]
truncate table [dbo].[DailyTransactionsCBOI]
truncate table [dbo].[DailyTransactionsIB]
truncate table [dbo].[DailyTransactionsPNB]
truncate table [dbo].[DailyTransactionsUBI]
truncate table [dbo].[DailyTransactionsUBGB]
truncate table [dbo].[LoanLeadReportsBOB]
truncate table [dbo].[LoanLeadReportsBOI]
truncate table [dbo].[LoanLeadReportsUBI]

truncate table [dbo].[FTDTransactions]
truncate table [dbo].[MTDTransactions]
truncate table [dbo].[TransactionFileUploadLogs]